### ISSUE TITLE
Not Responsive in Games

### ISSUE THREAD

**Issue by CarrotOmelette** [xerpi/vitastick#36]
[FIXED] - Used Steam Big Picture to configure the controller

I have managed to turn the PS Vita into a recognized controller and all buttons and analog stick work accordingly (I checked using Devices and Printers). I however, don't understand how I can use it in games. I have tried in Forza Horizon 4 and Hollow Knight, both tell me that they recognize or detect a controller but when I try to remap it, it just doesn't work (I select to remap a key, but then clicking on the PS Vita does not replace the button set before) and the keyboard is the only thing I can use still. Am I missing any extra steps? I would appreciate any help, thank you for reading!

**Comment by JacekJagosz** [comment]
[I couldn't make Vitastick work on my console, so I'm not 100% sure it will work]
If you don't have a common controller and have problems with game compatibility, there are a few options: X360CE and using Steam Big Picture. The first one is an exe you drop in a game folder that emulates an Xbox 360 controller and allows you you binding configuration. It doesn't work with Windows Store games though (so no Forza).
Steam Big Picture is a cleaner option, you need to launch big picture, go to controller settings, allow configuration of standard controllers, and then you can configure the controller bindings and such. It will obviously work for all your Steam games, for other there is an option to add non-Steam games to Steam, and for Windows Store games you will need to use a tool called GloSC.
Good luck and I hope it will work for you!
Oh and what Vita and software version are you using? I'm curious because it doesn't work on my OLED 3.60 ENSO, it just goes to sleep and disconnects from the PC

**Comment by CarrotOmelette** [comment]
Thank you so much! When I wrote this ticket I had 3.73 Vita, but now I have a 3.60 Enso spoofed Vita, so I don't know if this will change. I'll try it either way and get back with results!

**Comment by CarrotOmelette** [comment]
I have managed to once again download and run it just fine, with it being detected as a USB controller. I am now going to try your Steam Big Picture suggestion.

**Comment by CarrotOmelette** [comment]
It allowed me to set it up using Steam Big Picture, but when I got into Hollow Knight using Big Picture (with the controller still connected and detected) the Vita no longer worked and the control passed onto the keyboard. I will try to troubleshoot a bit more.
